disabled_rules:
  - trailing_whitespace
  - line_length
opt_in_rules:
  - empty_count
  - empty_string
included:
  - Packages
  - ShredMate
excluded:
  - Packages/*/Tests
  - .build
  - .git
analyzer_rules:
  - unused_import
line_length:
  warning: 120
  error: 150
identifier_name:
  min_length:
    warning: 1
  max_length:
    warning: 60
    error: 80
file_length:
  warning: 500
  error: 1000
type_body_length:
  warning: 300
  error: 400
function_body_length:
  warning: 50
  error: 100
cyclomatic_complexity:
  warning: 10
  error: 20
